* Jeepster

The 1948 Jeepster, known internally as the VJ-2) and as the VJ-673 in the
mechanic's manual.  Our jeepster has the original 4 cylinder "Go-Devil" L-134
engine.  Ours has no oil filter, which was optional.

Our serial number is 77220 (I think). The serial number plate is in pretty bad
shape. It was found behind the glove box however.

** Good parts sites

   [[http://www.kaiserwillys.com/about_willys_jeepster_vj_history_spec][Keaier Willy's Jeepster Specs]]
   [[http://www.willysamerica.com/][Willy's America]]

** Informational Links

   [[https://www.hemmings.com/blog/article/1948-1951-jeepster/][Heemings re. Jeepsters]]
   [[https://en.wikipedia.org/wiki/Willys-Overland_Jeepster#1948][Wikipedia]]

** Lubrication

| Unit                  | Type Lube             | Winter | Summer |         |
|-----------------------+-----------------------+--------+--------+---------|
| Chasis                | Chasis Oil            |      0 |      1 |         |
| Transmission          | Trans. Gear Oil       |     80 |     90 | 1.5 pts |
| Trans. Overdrive      | Trans. Gear Oil       |     80 |     90 | 1.5 pts |
| Transfer Case         | Trans. Gear Oil       |     80 |     90 |         |
| Differential Rear     | Hypoid Gear Oil       |     90 |     90 | 2 pts   |
| Differential Front    | Hypoid Gear Oil       |     90 |     90 |         |
| Steering Gear         | Steering Gear Oil     |    140 |    140 | 6 oz    |
| Wheel Bearings        | Wheel Bearing Greas   |      2 |      2 |         |
| Fan & Water Pump      | Sealed Bearing - None |        |        |         |
| Air Cleaner--Oil Bath | Engine Oil            |        |        | None    |
| Ignition Distributor  | Engine Oil            |        |        |         |
| Generator             | Engine Oil            |        |        |         |
| Starter               | Engine Oil            |        |        |         |
| Clutch                | Steering Gear Oil     |        |        |         |
| Engine                |                       |        |        | 4qts    |

** Notes

*** 2015-10-11

 Connal and I pulled out the gas tank.  There is a bit of scum in the bottom of
 the tank, which I think was floating on the surface of the gas.  Otherwise
 looks very clean.  I'm thinking of ways to get a better view of the whole
 thing.

 We cleaned up the outside, looks very nice.  We also removed the hood, and
 cleaned a bit of the front engine.  Despite the info we received in Nikki's
 cache, it looks like we have an original Willys Jeep engine.

 The distributor cap, and all the wires are brand new. I bet the plugs will be
 as well, though they show considerably more rust.

 Also cleaned the back a bit.  There is quite a bit of rust in the interior of
 the car.  Need a plan for that.

 We started some molasses soaks as a test.

 I'm thinking that we can use birch plywood panels in the interior of the car.
 sand blasted aluminum is another idea.


*** 2015-10-09

 First day of working on the Jeepster renovation.  My goal is just to get the
 old fluids, and junk to the hazardous waste site over the weekend.

 First, I drained the gas.  There still was about 3 gallons in the tank.  It
 came out a beautiful red color, and wasn't too sedimenty until the very end.
 Have see a few differenet methods of cleaning the tank.  Will remove it once I
 figure out the locked gas cap

 Next drained about 4 qts of blueish oil from the engine, and then about 3
 quarts of normal looking radiator fluid.  Still need to look at the brakes, and
 remove the oil filter, gas filter, spark plugs.
